### ISSUE TITLE
Grappling Hook out of world bounds causes IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ultimatejacob27** [squeeglii/grapplemod-restitched#15]
## Versions:

 - The Grapple Hook Mod:  1.7
 - Minecraft:  1.20.1
 - Mod Loader:  Fabric 0.15.6

This was being used in a large modpack. The server would crash but not the whole game. The error seemed to occur when trying to grapple into chunks that are still being loaded. The crash was in single player mode. Possibly relevant mods in the modpack included sodium, iris, lithium, bobby, better fps render distance, entity culling fabric/forge, no see no tick, dynamic view, debugify, chunk sending, and modernfix. Sorry if it isn't actually this mod's fault.

[17:17:36] [Netty Local Client IO #1/ERROR]: Encountered exception while handling in channel with name "grapplemod:segment"
java.lang.IndexOutOfBoundsException: Index: 8, Size: 2
	at java.util.LinkedList.checkElementIndex(LinkedList.java:559) ~[?:?]
	at java.util.LinkedList.remove(LinkedList.java:529) ~[?:?]
	at com.yyon.grapplinghook.entity.grapplehook.SegmentHandler.removeSegment(SegmentHandler.java:155) ~[grapplemod-1.20(.1)-v1.7.jar:?]
	at com.yyon.grapplinghook.network.clientbound.SegmentMessage.processMessage(SegmentMessage.java:98) ~[grapplemod-1.20(.1)-v1.7.jar:?]
	at com.yyon.grapplinghook.network.NetworkManager.lambda$generateClientPacketHandler$0(NetworkManager.java:25) ~[grapplemod-1.20(.1)-v1.7.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:40) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:90) ~[fabric-networking-api-v1-1.3.10+eeb8eb3677-5f0732b3ac824797.jar:?]
	at net.minecraft.class_634.handler$eld000$fabric-networking-api-v1$handleCustomPayload(class_634.java:3768) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:175) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:160) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:52) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.82.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.82.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.82.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by squeeglii** [comment]
Unable to recreate with just this mod so it's likely an incompatibility with another mod. I'll see if I can figure that out.

Could you send a full list of mods from that modpack, please? That or send a client log as that usually includes the mod list
